theme = "flexoki_dark"


[editor.lsp]
auto-signature-help = false
display-inlay-hints = false

[editor]
cursorline = true
true-color = true
auto-completion = false

[editor.inline-diagnostics]
cursor-line = "hint"
